/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UpsellingUmkmRouteImport } from './routes/upselling-umkm'
import { Route as TourUmkmRouteImport } from './routes/tour-umkm'
import { Route as TokoRouteImport } from './routes/toko'
import { Route as StepRouteImport } from './routes/step'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductRouteImport } from './routes/product'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpsellingUmkmIndexRouteImport } from './routes/upselling-umkm/index'
import { Route as TokoIndexRouteImport } from './routes/toko/index'
import { Route as StepIndexRouteImport } from './routes/step/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as ProductIndexRouteImport } from './routes/product/index'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as UpsellingUmkmArticleIdRouteImport } from './routes/upselling-umkm/$articleId'
import { Route as TokoStoreIdRouteImport } from './routes/toko/$storeId'
import { Route as StepTelpRouteImport } from './routes/step/telp'
import { Route as StepOtpRouteImport } from './routes/step/otp'
import { Route as StepDocRouteImport } from './routes/step/doc'
import { Route as ProfilePenjualRouteImport } from './routes/profile/penjual'
import { Route as ProfilePembeliRouteImport } from './routes/profile/pembeli'
import { Route as ProductReviewRouteImport } from './routes/product/review'
import { Route as ProductKonfirmasiPesananRouteImport } from './routes/product/konfirmasi-pesanan'
import { Route as ProductInfoRouteImport } from './routes/product/info'
import { Route as ProductCartRouteImport } from './routes/product/cart'
import { Route as ProductProductIdRouteImport } from './routes/product/$productId'
import { Route as AuthSingupRouteImport } from './routes/auth/singup'
import { Route as AuthSigninRouteImport } from './routes/auth/signin'

const UpsellingUmkmRoute = UpsellingUmkmRouteImport.update({
  id: '/upselling-umkm',
  path: '/upselling-umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const TourUmkmRoute = TourUmkmRouteImport.update({
  id: '/tour-umkm',
  path: '/tour-umkm',
  getParentRoute: () => rootRouteImport,
} as any)
const TokoRoute = TokoRouteImport.update({
  id: '/toko',
  path: '/toko',
  getParentRoute: () => rootRouteImport,
} as any)
const StepRoute = StepRouteImport.update({
  id: '/step',
  path: '/step',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRoute = ProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpsellingUmkmIndexRoute = UpsellingUmkmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => UpsellingUmkmRoute,
} as any)
const TokoIndexRoute = TokoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TokoRoute,
} as any)
const StepIndexRoute = StepIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StepRoute,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductIndexRoute = ProductIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductRoute,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const UpsellingUmkmArticleIdRoute = UpsellingUmkmArticleIdRouteImport.update({
  id: '/$articleId',
  path: '/$articleId',
  getParentRoute: () => UpsellingUmkmRoute,
} as any)
const TokoStoreIdRoute = TokoStoreIdRouteImport.update({
  id: '/$storeId',
  path: '/$storeId',
  getParentRoute: () => TokoRoute,
} as any)
const StepTelpRoute = StepTelpRouteImport.update({
  id: '/telp',
  path: '/telp',
  getParentRoute: () => StepRoute,
} as any)
const StepOtpRoute = StepOtpRouteImport.update({
  id: '/otp',
  path: '/otp',
  getParentRoute: () => StepRoute,
} as any)
const StepDocRoute = StepDocRouteImport.update({
  id: '/doc',
  path: '/doc',
  getParentRoute: () => StepRoute,
} as any)
const ProfilePenjualRoute = ProfilePenjualRouteImport.update({
  id: '/penjual',
  path: '/penjual',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePembeliRoute = ProfilePembeliRouteImport.update({
  id: '/pembeli',
  path: '/pembeli',
  getParentRoute: () => ProfileRoute,
} as any)
const ProductReviewRoute = ProductReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProductRoute,
} as any)
const ProductKonfirmasiPesananRoute =
  ProductKonfirmasiPesananRouteImport.update({
    id: '/konfirmasi-pesanan',
    path: '/konfirmasi-pesanan',
    getParentRoute: () => ProductRoute,
  } as any)
const ProductInfoRoute = ProductInfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => ProductRoute,
} as any)
const ProductCartRoute = ProductCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => ProductRoute,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => ProductRoute,
} as any)
const AuthSingupRoute = AuthSingupRouteImport.update({
  id: '/singup',
  path: '/singup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSigninRoute = AuthSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/product': typeof ProductRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/step': typeof StepRouteWithChildren
  '/toko': typeof TokoRouteWithChildren
  '/tour-umkm': typeof TourUmkmRoute
  '/upselling-umkm': typeof UpsellingUmkmRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/singup': typeof AuthSingupRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/cart': typeof ProductCartRoute
  '/product/info': typeof ProductInfoRoute
  '/product/konfirmasi-pesanan': typeof ProductKonfirmasiPesananRoute
  '/product/review': typeof ProductReviewRoute
  '/profile/pembeli': typeof ProfilePembeliRoute
  '/profile/penjual': typeof ProfilePenjualRoute
  '/step/doc': typeof StepDocRoute
  '/step/otp': typeof StepOtpRoute
  '/step/telp': typeof StepTelpRoute
  '/toko/$storeId': typeof TokoStoreIdRoute
  '/upselling-umkm/$articleId': typeof UpsellingUmkmArticleIdRoute
  '/auth/': typeof AuthIndexRoute
  '/product/': typeof ProductIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/step/': typeof StepIndexRoute
  '/toko/': typeof TokoIndexRoute
  '/upselling-umkm/': typeof UpsellingUmkmIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/tour-umkm': typeof TourUmkmRoute
  '/auth/signin': typeof AuthSigninRoute
  '/auth/singup': typeof AuthSingupRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/cart': typeof ProductCartRoute
  '/product/info': typeof ProductInfoRoute
  '/product/konfirmasi-pesanan': typeof ProductKonfirmasiPesananRoute
  '/product/review': typeof ProductReviewRoute
  '/profile/pembeli': typeof ProfilePembeliRoute
  '/profile/penjual': typeof ProfilePenjualRoute
  '/step/doc': typeof StepDocRoute
  '/step/otp': typeof StepOtpRoute
  '/step/telp': typeof StepTelpRoute
  '/toko/$storeId': typeof TokoStoreIdRoute
  '/upselling-umkm/$articleId': typeof UpsellingUmkmArticleIdRoute
  '/auth': typeof AuthIndexRoute
  '/product': typeof ProductIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/step': typeof StepIndexRoute
  '/toko': typeof TokoIndexRoute
  '/upselling-umkm': typeof UpsellingUmkmIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/product': typeof ProductRouteWithChildren
  '/profile': typeof ProfileRouteWithChildren
  '/step': typeof StepRouteWithChildren
  '/toko': typeof TokoRouteWithChildren
  '/tour-umkm': typeof TourUmkmRoute
  '/upselling-umkm': typeof UpsellingUmkmRouteWithChildren
  '/auth/signin': typeof AuthSigninRoute
  '/auth/singup': typeof AuthSingupRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/product/cart': typeof ProductCartRoute
  '/product/info': typeof ProductInfoRoute
  '/product/konfirmasi-pesanan': typeof ProductKonfirmasiPesananRoute
  '/product/review': typeof ProductReviewRoute
  '/profile/pembeli': typeof ProfilePembeliRoute
  '/profile/penjual': typeof ProfilePenjualRoute
  '/step/doc': typeof StepDocRoute
  '/step/otp': typeof StepOtpRoute
  '/step/telp': typeof StepTelpRoute
  '/toko/$storeId': typeof TokoStoreIdRoute
  '/upselling-umkm/$articleId': typeof UpsellingUmkmArticleIdRoute
  '/auth/': typeof AuthIndexRoute
  '/product/': typeof ProductIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/step/': typeof StepIndexRoute
  '/toko/': typeof TokoIndexRoute
  '/upselling-umkm/': typeof UpsellingUmkmIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/product'
    | '/profile'
    | '/step'
    | '/toko'
    | '/tour-umkm'
    | '/upselling-umkm'
    | '/auth/signin'
    | '/auth/singup'
    | '/product/$productId'
    | '/product/cart'
    | '/product/info'
    | '/product/konfirmasi-pesanan'
    | '/product/review'
    | '/profile/pembeli'
    | '/profile/penjual'
    | '/step/doc'
    | '/step/otp'
    | '/step/telp'
    | '/toko/$storeId'
    | '/upselling-umkm/$articleId'
    | '/auth/'
    | '/product/'
    | '/profile/'
    | '/step/'
    | '/toko/'
    | '/upselling-umkm/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/tour-umkm'
    | '/auth/signin'
    | '/auth/singup'
    | '/product/$productId'
    | '/product/cart'
    | '/product/info'
    | '/product/konfirmasi-pesanan'
    | '/product/review'
    | '/profile/pembeli'
    | '/profile/penjual'
    | '/step/doc'
    | '/step/otp'
    | '/step/telp'
    | '/toko/$storeId'
    | '/upselling-umkm/$articleId'
    | '/auth'
    | '/product'
    | '/profile'
    | '/step'
    | '/toko'
    | '/upselling-umkm'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/product'
    | '/profile'
    | '/step'
    | '/toko'
    | '/tour-umkm'
    | '/upselling-umkm'
    | '/auth/signin'
    | '/auth/singup'
    | '/product/$productId'
    | '/product/cart'
    | '/product/info'
    | '/product/konfirmasi-pesanan'
    | '/product/review'
    | '/profile/pembeli'
    | '/profile/penjual'
    | '/step/doc'
    | '/step/otp'
    | '/step/telp'
    | '/toko/$storeId'
    | '/upselling-umkm/$articleId'
    | '/auth/'
    | '/product/'
    | '/profile/'
    | '/step/'
    | '/toko/'
    | '/upselling-umkm/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  ProductRoute: typeof ProductRouteWithChildren
  ProfileRoute: typeof ProfileRouteWithChildren
  StepRoute: typeof StepRouteWithChildren
  TokoRoute: typeof TokoRouteWithChildren
  TourUmkmRoute: typeof TourUmkmRoute
  UpsellingUmkmRoute: typeof UpsellingUmkmRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upselling-umkm': {
      id: '/upselling-umkm'
      path: '/upselling-umkm'
      fullPath: '/upselling-umkm'
      preLoaderRoute: typeof UpsellingUmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tour-umkm': {
      id: '/tour-umkm'
      path: '/tour-umkm'
      fullPath: '/tour-umkm'
      preLoaderRoute: typeof TourUmkmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/toko': {
      id: '/toko'
      path: '/toko'
      fullPath: '/toko'
      preLoaderRoute: typeof TokoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/step': {
      id: '/step'
      path: '/step'
      fullPath: '/step'
      preLoaderRoute: typeof StepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product': {
      id: '/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof ProductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upselling-umkm/': {
      id: '/upselling-umkm/'
      path: '/'
      fullPath: '/upselling-umkm/'
      preLoaderRoute: typeof UpsellingUmkmIndexRouteImport
      parentRoute: typeof UpsellingUmkmRoute
    }
    '/toko/': {
      id: '/toko/'
      path: '/'
      fullPath: '/toko/'
      preLoaderRoute: typeof TokoIndexRouteImport
      parentRoute: typeof TokoRoute
    }
    '/step/': {
      id: '/step/'
      path: '/'
      fullPath: '/step/'
      preLoaderRoute: typeof StepIndexRouteImport
      parentRoute: typeof StepRoute
    }
    '/profile/': {
      id: '/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/product/': {
      id: '/product/'
      path: '/'
      fullPath: '/product/'
      preLoaderRoute: typeof ProductIndexRouteImport
      parentRoute: typeof ProductRoute
    }
    '/auth/': {
      id: '/auth/'
      path: '/'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/upselling-umkm/$articleId': {
      id: '/upselling-umkm/$articleId'
      path: '/$articleId'
      fullPath: '/upselling-umkm/$articleId'
      preLoaderRoute: typeof UpsellingUmkmArticleIdRouteImport
      parentRoute: typeof UpsellingUmkmRoute
    }
    '/toko/$storeId': {
      id: '/toko/$storeId'
      path: '/$storeId'
      fullPath: '/toko/$storeId'
      preLoaderRoute: typeof TokoStoreIdRouteImport
      parentRoute: typeof TokoRoute
    }
    '/step/telp': {
      id: '/step/telp'
      path: '/telp'
      fullPath: '/step/telp'
      preLoaderRoute: typeof StepTelpRouteImport
      parentRoute: typeof StepRoute
    }
    '/step/otp': {
      id: '/step/otp'
      path: '/otp'
      fullPath: '/step/otp'
      preLoaderRoute: typeof StepOtpRouteImport
      parentRoute: typeof StepRoute
    }
    '/step/doc': {
      id: '/step/doc'
      path: '/doc'
      fullPath: '/step/doc'
      preLoaderRoute: typeof StepDocRouteImport
      parentRoute: typeof StepRoute
    }
    '/profile/penjual': {
      id: '/profile/penjual'
      path: '/penjual'
      fullPath: '/profile/penjual'
      preLoaderRoute: typeof ProfilePenjualRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/pembeli': {
      id: '/profile/pembeli'
      path: '/pembeli'
      fullPath: '/profile/pembeli'
      preLoaderRoute: typeof ProfilePembeliRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/product/review': {
      id: '/product/review'
      path: '/review'
      fullPath: '/product/review'
      preLoaderRoute: typeof ProductReviewRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/konfirmasi-pesanan': {
      id: '/product/konfirmasi-pesanan'
      path: '/konfirmasi-pesanan'
      fullPath: '/product/konfirmasi-pesanan'
      preLoaderRoute: typeof ProductKonfirmasiPesananRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/info': {
      id: '/product/info'
      path: '/info'
      fullPath: '/product/info'
      preLoaderRoute: typeof ProductInfoRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/cart': {
      id: '/product/cart'
      path: '/cart'
      fullPath: '/product/cart'
      preLoaderRoute: typeof ProductCartRouteImport
      parentRoute: typeof ProductRoute
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof ProductRoute
    }
    '/auth/singup': {
      id: '/auth/singup'
      path: '/singup'
      fullPath: '/auth/singup'
      preLoaderRoute: typeof AuthSingupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/signin': {
      id: '/auth/signin'
      path: '/signin'
      fullPath: '/auth/signin'
      preLoaderRoute: typeof AuthSigninRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSigninRoute: typeof AuthSigninRoute
  AuthSingupRoute: typeof AuthSingupRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSigninRoute: AuthSigninRoute,
  AuthSingupRoute: AuthSingupRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProductRouteChildren {
  ProductProductIdRoute: typeof ProductProductIdRoute
  ProductCartRoute: typeof ProductCartRoute
  ProductInfoRoute: typeof ProductInfoRoute
  ProductKonfirmasiPesananRoute: typeof ProductKonfirmasiPesananRoute
  ProductReviewRoute: typeof ProductReviewRoute
  ProductIndexRoute: typeof ProductIndexRoute
}

const ProductRouteChildren: ProductRouteChildren = {
  ProductProductIdRoute: ProductProductIdRoute,
  ProductCartRoute: ProductCartRoute,
  ProductInfoRoute: ProductInfoRoute,
  ProductKonfirmasiPesananRoute: ProductKonfirmasiPesananRoute,
  ProductReviewRoute: ProductReviewRoute,
  ProductIndexRoute: ProductIndexRoute,
}

const ProductRouteWithChildren =
  ProductRoute._addFileChildren(ProductRouteChildren)

interface ProfileRouteChildren {
  ProfilePembeliRoute: typeof ProfilePembeliRoute
  ProfilePenjualRoute: typeof ProfilePenjualRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfilePembeliRoute: ProfilePembeliRoute,
  ProfilePenjualRoute: ProfilePenjualRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface StepRouteChildren {
  StepDocRoute: typeof StepDocRoute
  StepOtpRoute: typeof StepOtpRoute
  StepTelpRoute: typeof StepTelpRoute
  StepIndexRoute: typeof StepIndexRoute
}

const StepRouteChildren: StepRouteChildren = {
  StepDocRoute: StepDocRoute,
  StepOtpRoute: StepOtpRoute,
  StepTelpRoute: StepTelpRoute,
  StepIndexRoute: StepIndexRoute,
}

const StepRouteWithChildren = StepRoute._addFileChildren(StepRouteChildren)

interface TokoRouteChildren {
  TokoStoreIdRoute: typeof TokoStoreIdRoute
  TokoIndexRoute: typeof TokoIndexRoute
}

const TokoRouteChildren: TokoRouteChildren = {
  TokoStoreIdRoute: TokoStoreIdRoute,
  TokoIndexRoute: TokoIndexRoute,
}

const TokoRouteWithChildren = TokoRoute._addFileChildren(TokoRouteChildren)

interface UpsellingUmkmRouteChildren {
  UpsellingUmkmArticleIdRoute: typeof UpsellingUmkmArticleIdRoute
  UpsellingUmkmIndexRoute: typeof UpsellingUmkmIndexRoute
}

const UpsellingUmkmRouteChildren: UpsellingUmkmRouteChildren = {
  UpsellingUmkmArticleIdRoute: UpsellingUmkmArticleIdRoute,
  UpsellingUmkmIndexRoute: UpsellingUmkmIndexRoute,
}

const UpsellingUmkmRouteWithChildren = UpsellingUmkmRoute._addFileChildren(
  UpsellingUmkmRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  ProductRoute: ProductRouteWithChildren,
  ProfileRoute: ProfileRouteWithChildren,
  StepRoute: StepRouteWithChildren,
  TokoRoute: TokoRouteWithChildren,
  TourUmkmRoute: TourUmkmRoute,
  UpsellingUmkmRoute: UpsellingUmkmRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
